import { useState, useRef, useCallback, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { Navbar } from './Navbar'
import { UserProfile } from './GoogleLogin'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

const API_BASE = (import.meta.env.VITE_API_BASE ?? '').replace(/\/$/, '')

async function queryLegal(question, topK = 5) {
  const endpoint = API_BASE ? `${API_BASE}/api/query` : '/api/query'
  const token = localStorage.getItem('auth_token')
  const headers = {
    'Content-Type': 'application/json',
    'ngrok-skip-browser-warning': 'true',
  }
  
  if (token) {
    headers['Authorization'] = `Bearer ${token}`
  }

  const res = await fetch(endpoint, {
    method: 'POST',
    headers,
    credentials: 'include',
    body: JSON.stringify({ question, top_k: topK, mode: 'hyde' }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.detail ?? `HTTP ${res.status}`)
  }
  return res.json()
}

async function queryLegalWithMode(question, topK, mode) {
  const endpoint = API_BASE ? `${API_BASE}/api/query` : '/api/query'
  const token = localStorage.getItem('auth_token')
  const headers = {
    'Content-Type': 'application/json',
    'ngrok-skip-browser-warning': 'true',
  }

  if (token) {
    headers['Authorization'] = `Bearer ${token}`
  }

  const res = await fetch(endpoint, {
    method: 'POST',
    headers,
    credentials: 'include',
    body: JSON.stringify({ question, top_k: topK, mode }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err.detail ?? `HTTP ${res.status}`)
  }
  return res.json()
}

const SAMPLES = [
  'लोक सेवा आयोगको मुख्य काम के हो?',
  'श्रम ऐन अनुसार कामदारलाई कति बिदा पाइन्छ?',
  'बालबालिका ऐनले बाल श्रम सम्बन्धमा के भन्छ?',
  'सम्बन्ध विच्छेद कसरी प्राप्त गर्ने?',
  'नागरिकको मौलिक हक के हो?',
]

function Spinner({ size = 'sm' }) {
  const cls = size === 'lg' ? 'w-8 h-8 border-[3px]' : 'w-4 h-4 border-2'
  const style = { borderColor: '#E0D9CC', borderTopColor: '#8B7355' }
  return <span className={`${cls} rounded-full animate-spin inline-block flex-shrink-0`} style={style} />
}

function ChevronIcon({ open }) {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      style={{ transform: open ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.2s ease' }}
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  )
}

function Collapsible({ badge, badgeClass, badgeStyle, label, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="rounded-xl overflow-hidden bg-white shadow-sm" style={{ borderColor: '#C4BAA8', border: '1px solid #C4BAA8' }}>
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center gap-3 px-4 py-3 transition-colors text-left"
        style={{ '&:hover': { background: '#F5F0E6' } }}
        onMouseEnter={(e) => { e.currentTarget.style.background = '#F5F0E6' }}
        onMouseLeave={(e) => { e.currentTarget.style.background = 'white' }}
      >
        <span className={`text-[10px] font-bold tracking-widest uppercase px-2 py-0.5 rounded-md border flex-shrink-0 ${badgeClass}`} style={badgeStyle}>
          {badge}
        </span>
        <span className="text-xs font-medium flex-1" style={{ color: '#5A5245' }}>{label}</span>
        <span className="flex-shrink-0" style={{ color: '#C4BAA8' }}><ChevronIcon open={open} /></span>
      </button>
      {open && <div style={{ borderTop: '1px solid #C4BAA8' }}>{children}</div>}
    </div>
  )
}

function HydeCard({ passage }) {
  return (
    <Collapsible
      badge="hyde"
      badgeClass="text-white border" 
      badgeStyle={{ background: '#8B7355', borderColor: '#8B7355' }}
      label="Hypothetical legal passage generated by the fine-tuned SLM"
    >
      <div className="p-4" style={{ background: '#F5F0E6' }}>
        <p className="font-mono text-[11px] leading-relaxed whitespace-pre-wrap" style={{ color: '#5A5245' }}>{passage}</p>
      </div>
    </Collapsible>
  )
}

function DocsCard({ docs, badge, badgeClass, badgeStyle, label }) {
  const [expanded, setExpanded] = useState(null)
  return (
    <Collapsible badge={badge} badgeClass={badgeClass} badgeStyle={badgeStyle} label={label}>
      <div style={{ borderTop: '1px solid #C4BAA8' }}>
        {docs.map((doc, i) => (
          <div key={i} style={{ borderBottom: i < docs.length - 1 ? '1px solid #C4BAA8' : 'none' }}>
            <button
              onClick={() => setExpanded(expanded === i ? null : i)}
              className="w-full flex items-center gap-3 px-4 py-2.5 transition-colors text-left"
              onMouseEnter={(e) => { e.currentTarget.style.background = '#F5F0E6' }}
              onMouseLeave={(e) => { e.currentTarget.style.background = 'white' }}
            >
              <span className="w-5 h-5 rounded-full text-[10px] font-bold flex items-center justify-center flex-shrink-0" style={{ background: '#D6CDB8', color: '#8B7355' }}>
                {i + 1}
              </span>
              <span className="text-xs truncate flex-1 font-mono" style={{ color: '#5A5245' }}>
                {doc.slice(0, 90).replace(/\n/g, ' ')}...
              </span>
              <span className="flex-shrink-0" style={{ color: '#C4BAA8' }}><ChevronIcon open={expanded === i} /></span>
            </button>
            {expanded === i && (
              <div className="px-4 pb-3 pl-12">
                <p className="font-mono text-[11px] leading-relaxed whitespace-pre-wrap bg-white rounded-lg p-3" style={{ borderColor: '#C4BAA8', border: '1px solid #C4BAA8', color: '#5A5245' }}>
                  {doc}
                </p>
              </div>
            )}
          </div>
        ))}
      </div>
    </Collapsible>
  )
}

function AnswerCard({ title, label, answer, bgGradient, icon }) {
  return (
    <div className="rounded-xl overflow-hidden border bg-white h-full flex flex-col" style={{ borderColor: '#C4BAA8', boxShadow: '0 2px 8px rgba(139, 115, 85, 0.08)' }}>
      <div className={`flex items-center gap-3 px-4 py-3`} style={{ background: title === 'Agent' ? 'linear-gradient(to right, #5A5245, #3D3530)' : 'linear-gradient(to right, #8B7355, #6B563D)' }}>
        <span className="text-[10px] font-bold tracking-widest uppercase px-2 py-0.5 rounded-md text-white border flex-shrink-0" style={{ background: 'rgba(255, 255, 255, 0.2)', borderColor: 'rgba(255, 255, 255, 0.25)' }}>
          {title}
        </span>
        <span className="text-xs font-medium text-white/90">{label}</span>
        <svg className="ml-auto flex-shrink-0" width="14" height="14" viewBox="0 0 24 24" fill="white" opacity="0.5">
          {icon}
        </svg>
      </div>
      <div className="p-5 text-sm leading-[1.9] flex-1 overflow-auto" style={{ color: '#1a1208' }}>
        <ReactMarkdown 
          remarkPlugins={[remarkGfm]}
          components={{
            p: ({node, ...props}) => <p className="mb-3 last:mb-0" {...props} />,
            ul: ({node, ...props}) => <ul className="list-disc pl-5 mb-3 space-y-1" {...props} />,
            ol: ({node, ...props}) => <ol className="list-decimal pl-5 mb-3 space-y-1" {...props} />,
            li: ({node, ...props}) => <li className="pl-1" {...props} />,
            h3: ({node, ...props}) => <h3 className="text-base font-bold mt-4 mb-2 text-gray-900" {...props} />,
            h4: ({node, ...props}) => <h4 className="text-sm font-bold mt-3 mb-1 text-gray-900" {...props} />,
            strong: ({node, ...props}) => <strong className="font-semibold" style={{ color: '#1a1208' }} {...props} />,
            table: ({node, ...props}) => <div className="overflow-x-auto mb-3"><table className="min-w-full divide-y divide-gray-200 border" {...props} /></div>,
            th: ({node, ...props}) => <th className="px-3 py-2 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider border" {...props} />,
            td: ({node, ...props}) => <td className="px-3 py-2 whitespace-nowrap text-sm text-gray-700 border" {...props} />
          }}
        >
          {answer}
        </ReactMarkdown>
      </div>
    </div>
  )
}

function PipelineStep({ num, label, status }) {
  const styles = {
    waiting: { borderColor: '#E0D9CC', background: 'white', color: '#C4BAA8' },
    active: { borderColor: '#8B7355', background: '#8B7355', color: 'white', boxShadow: '0 4px 12px rgba(139, 115, 85, 0.2)' },
    done: { borderColor: '#5A5245', background: '#5A5245', color: 'white' },
  }[status]
  const lblColor = {
    waiting: '#C4BAA8',
    active: '#8B7355',
    done: '#5A5245',
  }[status]
  return (
    <div className="flex flex-col items-center gap-2">
      <div className="w-8 h-8 rounded-full border-2 text-xs font-semibold flex items-center justify-center flex-shrink-0" style={styles}>{num}</div>
      <span className="text-[11px] font-semibold text-center leading-tight" style={{ color: lblColor }}>{label}</span>
    </div>
  )
}

function LoadingView({ phase, mode }) {
  const idx = ['hyde', 'retrieve', 'answer'].indexOf(phase)
  const st = (i) => i < idx ? 'done' : i === idx ? 'active' : 'waiting'
  const line = (active) => (
    <div className="flex-1 flex items-start pt-4">
      <div className={`h-px w-full transition-colors duration-500`} style={{ background: active ? '#8B7355' : '#E0D9CC' }} />
    </div>
  )
  return (
    <div className="bg-white rounded-2xl px-8 py-10 text-center shadow-sm" style={{ borderColor: '#C4BAA8', border: '1px solid #C4BAA8' }}>
      <div className="flex justify-center mb-5"><Spinner size="lg" /></div>
      <p className="text-sm font-semibold mb-1" style={{ color: '#1a1208' }}>Processing your query</p>
      <p className="text-xs mb-8" style={{ color: '#5A5245' }}>
        {mode === 'agent'
          ? 'Agent mode: uses tools for deeper research'
          : 'HyDE mode: generates a HyDE passage, retrieves docs, and answers'}
      </p>
      <div className="flex items-start gap-2 max-w-sm mx-auto">
        <PipelineStep num="1" label={mode === 'agent' ? 'Plan' : 'Generate HyDE'} status={st(0)} />
        {line(idx >= 1)}
        <PipelineStep num="2" label={mode === 'agent' ? 'Use tools' : 'Retrieve docs'} status={st(1)} />
        {line(idx >= 2)}
        <PipelineStep num="3" label="Answer" status={st(2)} />
      </div>
    </div>
  )
}

export function Chat({ user, onLogout }) {
  const [question, setQuestion] = useState('')
  const [mode, setMode] = useState('hyde')
  const [loading, setLoading] = useState(false)
  const [phase, setPhase] = useState('hyde')
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const [history, setHistory] = useState([])
  const [showEnglish, setShowEnglish] = useState(false)
  
  const textareaRef = useRef(null)
  const scrollRef = useRef(null)

  useEffect(() => {
    const ta = textareaRef.current
    if (!ta) return
    ta.style.height = 'auto'
    ta.style.height = `${Math.min(ta.scrollHeight, 160)}px`
  }, [question])

  // Auto-scroll to bottom of results when new result arrives
  useEffect(() => {
    if (result || error) {
      setTimeout(() => {
        scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' })
      }, 100)
    }
  }, [result, error])

  const handleSubmit = useCallback(async (q = question) => {
    const trimmed = q.trim()
    if (!trimmed || loading) return
    setQuestion(trimmed)
    setLoading(true)
    setError(null)
    setResult(null)
    setShowEnglish(false)
    setPhase('hyde')
    
    const t1 = setTimeout(() => setPhase('retrieve'), 3000)
    const t2 = setTimeout(() => setPhase('answer'), 7000)
    try {
      const data = await queryLegalWithMode(trimmed, 5, mode)
      setResult(data)
      clearTimeout(t1)
      clearTimeout(t2)
      setHistory(h => [{ question: trimmed, time: new Date().toLocaleTimeString() }, ...h].slice(0, 6))
    } catch (e) {
      clearTimeout(t1)
      clearTimeout(t2)
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }, [question, loading, mode])

  const handleKey = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSubmit()
    }
  }

  return (
    <div
      className="h-screen flex flex-col overflow-hidden"
      style={{
        background: '#EDE8DC',
        fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif",
      }}
    >
      <Navbar user={user} onLogout={onLogout} />

      {/* Scrollable response area */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
        <div className="max-w-4xl mx-auto w-full px-4 sm:px-6 py-6">
          {/* Empty state */}
          {!loading && !result && !error && (
            <div className="flex flex-col items-center justify-center py-24 px-8 text-center">
              <div
                className="w-14 h-14 rounded-2xl flex items-center justify-center mb-5"
                style={{ background: '#F5F0E6' }}
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#8B7355" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M12 1L3 5v6c0 5.25 3.75 10.15 9 11.35C17.25 21.15 21 16.25 21 11V5L12 1z" />
                </svg>
              </div>
              <p
                className="text-base font-semibold mb-2"
                style={{ color: '#1a1208' }}
              >
                नेपाली कानूनी सहायक
              </p>
              <p
                className="text-sm max-w-md leading-relaxed mb-8"
                style={{ color: '#5A5245', fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", fontWeight: 500 }}
              >
                Ask any question about Nepal's laws and Constitution. Get instant answers grounded in legal sources with full citations.
              </p>
              
              {/* Sample questions */}
              <div className="w-full max-w-lg">
                <p
                  className="text-[10px] font-bold tracking-widest uppercase mb-3"
                  style={{ color: '#8B7355' }}
                >
                  Try These Questions
                </p>
                <div className="grid gap-2">
                  {SAMPLES.map(q => (
                    <button
                      key={q}
                      onClick={() => { setQuestion(q); textareaRef.current?.focus() }}
                      disabled={loading}
                      className="w-full text-left text-[13px] px-4 py-3 rounded-lg transition-all disabled:opacity-40 leading-snug shadow-sm"
                      style={{
                        color: '#1a1208',
                        background: '#F5F0E6',
                        border: '1px solid #C4BAA8',
                      }}
                      onMouseEnter={(e) => {
                        e.target.style.background = '#D6CDB8'
                        e.target.style.borderColor = '#8B7355'
                      }}
                      onMouseLeave={(e) => {
                        e.target.style.background = '#F5F0E6'
                        e.target.style.borderColor = '#C4BAA8'
                      }}
                    >
                      {q}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Error */}
          {error && (
            <div className="flex items-start gap-3 bg-red-50 border border-red-200 rounded-xl p-4 mb-4">
              <svg className="text-red-400 flex-shrink-0 mt-0.5" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
                <line x1="12" y1="9" x2="12" y2="13" />
                <line x1="12" y1="17" x2="12.01" y2="17" />
              </svg>
              <div>
                <p className="text-sm font-semibold text-red-700 mb-0.5">Request failed</p>
                <p className="text-xs text-red-500">{error}</p>
                <p className="text-xs text-red-400 mt-1">Check that `VITE_API_BASE` points to your running backend.</p>
              </div>
            </div>
          )}

          {/* Loading */}
          {loading && <LoadingView phase={phase} mode={mode} />}

          {/* Results */}
          {result && !loading && (
            <div className="space-y-3" style={{ animation: 'fadeUp 0.35s ease' }}>
              {/* Question echo */}
              <div className="flex items-start gap-3 mb-4">
                <div className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5" style={{ background: '#F5F0E6' }}>
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#8B7355" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" /><circle cx="12" cy="7" r="4" />
                  </svg>
                </div>
                <div>
                  <p className="text-sm font-semibold" style={{ color: '#1a1208' }}>{result.question}</p>
                  <p className="text-[11px] mt-0.5" style={{ color: '#5A5245' }}>Mode: {result.mode} · {result.processing_time}s</p>
                </div>
              </div>

              {result.mode === 'hyde' && result.hyde_passage && (
                <HydeCard passage={result.hyde_passage} />
              )}

              {result.mode === 'hyde' && Array.isArray(result.retrieved_docs) && (
                <DocsCard
                  docs={result.retrieved_docs}
                  badge="hyde ctx"
                  badgeClass="text-white"
                  badgeStyle={{ background: '#5A5245', borderColor: '#5A5245' }}
                  label={`${result.retrieved_docs.length} passages retrieved by HyDE RAG`}
                />
              )}
              
              <div className="flex items-center justify-end mt-4 mb-2 pr-1">
                <button
                  onClick={() => setShowEnglish(!showEnglish)}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-md bg-white transition-colors shadow-sm"
                style={{ borderColor: '#C4BAA8', border: '1px solid #C4BAA8', color: '#8B7355' }}
                onMouseEnter={(e) => { e.currentTarget.style.background = '#F5F0E6' }}
                onMouseLeave={(e) => { e.currentTarget.style.background = 'white' }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <circle cx="12" cy="12" r="10"></circle>
                    <line x1="2" y1="12" x2="22" y2="12"></line>
                    <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>
                  </svg>
                  {showEnglish ? 'View Original in Nepali' : 'Translate to English'}
                </button>
              </div>

              <AnswerCard
                title={result.mode === 'agent' ? 'Agent' : 'HyDE'}
                label={result.mode === 'agent' ? 'Tool-based research mode' : 'HyDE RAG answer'}
                answer={showEnglish && result.answer_in_english ? result.answer_in_english : result.answer}
                icon={
                  result.mode === 'agent'
                    ? <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zm1 14.5h-2V15h2zm1.9-6.1-1 .9A3.1 3.1 0 0 0 13 13h-2v-.5a4.1 4.1 0 0 1 1.2-2.9l1.3-1.2a1.7 1.7 0 1 0-2.9-1.2H8.6a3.7 3.7 0 1 1 6.3 2.5z" />
                    : <path d="M12 2l2.4 7.6H22l-6.2 4.5 2.4 7.5L12 17.1l-6.2 4.5 2.4-7.5L2 9.6h7.6z" />
                }
              />
            </div>
          )}
        </div>
      </div>

      {/* Input area pinned at bottom — Perplexity-style card */}
      <div
        className="px-4 sm:px-6 pb-4 pt-2"
        style={{ background: '#EDE8DC' }}
      >
        <div className="max-w-4xl mx-auto w-full">
          <div
            className="rounded-2xl border shadow-lg overflow-hidden"
            style={{
              background: '#F5F0E6',
              borderColor: '#C4BAA8',
              boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
            }}
          >
            {/* Textarea */}
            <div className="px-5 pt-4 pb-2">
              <textarea
                ref={textareaRef}
                rows={1}
                value={question}
                onChange={e => setQuestion(e.target.value)}
                onKeyDown={handleKey}
                disabled={loading}
                placeholder="नेपाली वा अंग्रेजीमा प्रश्न सोध्नुहोस्... (Ask in Nepali or English)"
                className="w-full resize-none text-[15px] placeholder-gray-400 bg-transparent outline-none leading-relaxed disabled:opacity-50"
                style={{
                  minHeight: '28px',
                  maxHeight: '120px',
                  overflowY: 'auto',
                  color: '#1a1208',
                }}
              />
            </div>

            {/* Toolbar row */}
            <div className="px-4 pb-3 pt-1 flex items-center justify-between">
              {/* Left — Mode dropdown */}
              <div className="flex items-center gap-2">
                <select
                  value={mode}
                  onChange={(e) => setMode(e.target.value)}
                  disabled={loading}
                  className="h-8 px-3 pr-7 text-[12px] font-semibold rounded-lg outline-none cursor-pointer disabled:opacity-50 transition-colors"
                  style={{
                    color: '#1a1208',
                    background: '#D6CDB8',
                    borderColor: '#8B7355',
                    border: '1px solid #8B7355',
                  }}
                >
                  <option value="hyde">⚡ HyDE (fast)</option>
                  <option value="agent">🤖 Agent (deep)</option>
                </select>
              </div>

              {/* Right — Send button */}
              <button
                onClick={() => handleSubmit()}
                disabled={loading || !question.trim()}
                className="flex items-center justify-center w-9 h-9 text-white rounded-lg transition-colors cursor-pointer disabled:cursor-not-allowed shadow-sm"
                style={{
                  background: loading || !question.trim() ? '#D6CDB8' : '#8B7355',
                }}
                onMouseEnter={(e) => {
                  if (!loading && question.trim()) e.currentTarget.style.background = '#6B563D'
                }}
                onMouseLeave={(e) => {
                  if (!loading && question.trim()) e.currentTarget.style.background = '#8B7355'
                }}
              >
                {loading
                  ? <Spinner />
                  : <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="22" y1="2" x2="11" y2="13" /><polygon points="22 2 15 22 11 13 2 9 22 2" /></svg>
                }
              </button>
            </div>
          </div>

          <p className="text-[10px] mt-2 text-center" style={{ color: '#5A5245' }}>
            <kbd className="font-mono px-1 py-px rounded text-[10px]" style={{ background: '#F5F0E6', color: '#8B7355', border: '1px solid #C4BAA8' }}>Enter</kbd> to send · <kbd className="font-mono px-1 py-px rounded text-[10px]" style={{ background: '#F5F0E6', color: '#8B7355', border: '1px solid #C4BAA8' }}>Shift+Enter</kbd> new line
          </p>
        </div>
      </div>

      <style>{`
        @keyframes fadeUp {
          from { opacity: 0; transform: translateY(10px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        /* Hide scrollbar but keep scrollable */
        div::-webkit-scrollbar {
          display: none;
        }
      `}</style>
    </div>
  )
}

